language: node_js
sudo: required
node_js: stable
cache:
  directories:
  - node_modules
script:
- yarn flow
- yarn test
- yarn test -- --coverage
branches:
  except:
  - gh-pages
before_deploy:
- yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build/
  target_branch: gh-pages
  on:
    branch: master
notifications:
  email:
    recipients:
      - lehoanganh25991@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
  slack:
    template:
      - "Build <%{build_url}|#%{build_number}> of %{repository_name} %{result} in %{duration}\n%{commit_message}"
    rooms:
      secure: nOybAikdszukhCfozPzyzW2sN0cyOX3nZ1B3uHgYcvtleHUDI9mW2KiLz6mFVZ3WJjaj5dpVif99PbTDynF8DdTvSEzhNsyby+fNtYdbJ5DnCl8c1NSGEod+ul1AL8x+xXFYhj2M0QJaBcn1WlbmWCNluRZmb1C4abh/uGAC7FpSjqZ1CTt2rWTJa7kepQ80Kv8rBDBA93e7Wfj0NA6zEw36Cpfk8VF+ORmx276fogH6gJlfItkPMLjuKl17FmsxJEtS2Uq4HdQoWGkt2Zkt/rCLFWZ4o0MAYQICrlE3Zb33JuuAwPjoJxmYKJ83Yuz2WZ2jfb6ZDOpE4SOBdqP9dwfYeJXRBPksSozQaIEF8eZC3YT6hRe0BqdsFxPvNUURXrCuhjoHncKV4ZWMK4LL12rKXD1CGylZKE3m4WIWnphmS410keXOypYbSCOBvOL2uUGk4D1Ix2FalJjXhv2BrsIrLiB6zC08xKpGM9LYFvqEL43YFkQNAerqmLGqXL5/Wi9QT/AtOfwNTrTGC+kIQuiPpG2oXGj9gYQ8Imj0oPLMxnbYaLcCGlvYLBtdCK3uar2MUw6adBpUjNVzfwKp9qHLfza0UHzJIQUqjmzNtXYEZGiCf1NU7UNsOm8vgglUForhublhJAt/TiImyMitJdeomu6ocmIJajvUy6VqoTk=
    on_success: always
    on_failure: always
dist: trusty
group: edge  # Add this
## try with cctray, travis api show baged on windows
## travis is greate, BUTTTT many tool look like 50 years ago

